"""empty message

Revision ID: 37572c8ab6ab
Revises: 
Create Date: 2019-05-24 07:44:57.115881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37572c8ab6ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nasabah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=True),
    sa.Column('kode_urutan', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.String(length=20), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=20), nullable=True),
    sa.Column('tanggal_lahir', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('nomer_hp', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sampah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.Column('kode', sa.String(length=20), nullable=True),
    sa.Column('kode_urutan', sa.String(length=20), nullable=True),
    sa.Column('tanggal', sa.String(length=20), nullable=True),
    sa.Column('jenis_sampah', sa.String(length=20), nullable=True),
    sa.Column('berat_sampah', sa.Integer(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('nasabah_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nasabah_id'], ['nasabah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabungan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=True),
    sa.Column('kode_urutan', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.Column('tanggal', sa.String(length=20), nullable=True),
    sa.Column('debet', sa.Integer(), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('nasabah_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nasabah_id'], ['nasabah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jenis_transaksi', sa.String(length=20), nullable=True),
    sa.Column('kode', sa.String(length=20), nullable=True),
    sa.Column('kode_urutan', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.Column('tanggal', sa.String(length=20), nullable=True),
    sa.Column('jumlah_transaksi', sa.Integer(), nullable=True),
    sa.Column('tujuan_transaksi', sa.String(length=20), nullable=True),
    sa.Column('status_transaksi', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('nasabah_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nasabah_id'], ['nasabah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('tabungan')
    op.drop_table('sampah')
    op.drop_table('nasabah')
    op.drop_table('admin')
    # ### end Alembic commands ###
